window.OwnWordsLexicon = window.OwnWordsLexicon || {};
window.OwnWordsLexicon.PHRASES = [
    ['in order to',['to'],3],['due to the fact that',['because','since'],3],['for the purpose of',['to','for'],3],['at this point in time',['now'],3],['in the event that',['if'],3],
    ['a large number of',['many','numerous'],3],['a significant number of',['many','a substantial number of'],3],['a wide range of',['many','a variety of','varied'],3],['the vast majority of',['most'],3],
    ['has the ability to',['can','is able to'],3],['have the ability to',['can','are able to'],3],['is able to',['can'],3],['are able to',['can'],3],['may be able to',['might be able to'],3],
    ['it is important to note that',['notably,','it is worth noting that'],3],['it is worth noting that',['notably,','notice that'],3],['it should be noted that',['notably,'],3],['it is important to remember that',['remember that'],3],
    ['in today\'s world',['today'],3],['in the modern world',['today','in modern life'],3],['on a daily basis',['daily','every day'],3],['on a regular basis',['regularly'],3],['in close proximity to',['near'],3],
    ['with regard to',['about','regarding'],3],['with respect to',['about','regarding'],3],['in relation to',['about','relative to'],2],['in terms of',['for','regarding'],2],
    ['in addition to',['besides','along with'],2],['as well as',['along with','and'],2],['as a result of',['because of','from'],2],['as a result',['so','consequently'],2],['for this reason',['therefore','so'],2],
    ['in spite of the fact that',['although','even though'],3],['despite the fact that',['although','even though'],3],['the reason why',['the reason','why'],2],['the fact that',['that'],2],
    ['serves as a reminder that',['reminds us that','shows that'],2],['serves to highlight',['highlights','shows'],3],['can be seen as',['can be viewed as','is arguably'],2],['when it comes to',['for','when considering'],2],
    ['from the perspective of',['from the view of','for'],2],['at the same time',['meanwhile','still'],2],['as a means of',['to','as a way to'],3],['in many cases',['often'],3],['in most cases',['usually'],3],['in some cases',['sometimes'],3],
    ['for example',['for instance'],3],['for instance',['for example'],3],['in other words',['put differently'],3],['on the other hand',['by contrast'],3],['in contrast',['by contrast'],3],['by contrast',['in contrast'],3],
    ['in fact',['actually'],2],['in particular',['especially'],2],['in general',['generally'],3],['a lot of',['many','plenty of'],2],['kind of',['somewhat'],2],['sort of',['somewhat'],2],
    ['is likely to',['will probably'],2],['are likely to',['will probably'],2],['this means that',['so','that means'],2],['this suggests that',['this indicates that','this points to the idea that'],2],
    ['take into account',['consider'],3],['keep in mind',['remember'],3],['make sure',['ensure'],3],['helps to',['helps'],2],['allows you to',['lets you'],3],['allows users to',['lets users'],3],
    ['plays a crucial role in',['is central to','matters greatly to','is important to'],2],['play a crucial role in',['are central to','matter greatly to','are important to'],2],
    ['native to',['found naturally in','native to'],2],['laced with',['containing','loaded with'],2],['adept at',['good at','well suited to'],2],
    ['the payoff is',['the benefit is','the advantage is'],2],['the cost is',['the tradeoff is','the downside is'],2],['a handful of',['only a few','a small number of'],3],
    ['get most of their water from',['take in most of their water from','obtain most of their water from'],2],['is often said to derive from',['is often said to come from','is commonly traced to'],3],
    ['nearly indistinguishable from',['extremely difficult to distinguish from','remarkably similar to'],2],['for gripping',['to grip'],3],['far too deep for',['surprisingly deep for','much deeper than expected for'],2],
    ['listed as endangered',['classified as endangered'],3],['hit populations hard',['severely reduced populations','badly damaged populations'],1],
    ['picky even within',['selective even within','choosy even within'],2],['favoring',['preferring'],3],['so tight they',['so tight that they'],3],
    ['survivor bias',['selection bias among survivors','a survivors-only view'],1],["what i've found more useful than",["i've found more useful than"],1],['spend a lot of energy',['put a lot of effort into','use a lot of energy'],2],
    ['the whole trick',['the core idea','basically the whole idea'],3],["i keep noticing",['i keep seeing',"i've been noticing"],2],['a lot of it comes down to',['much of it comes down to','often it comes down to'],3],
    ['the interesting finding is that',["what's interesting is that",'the interesting part is that'],3],['limiting factor',['constraint','main constraint'],3],['what limits',['what constrains','what holds back'],2],['concretely',['in practice','more specifically'],3],
    ['not because',['the reason is not'],1],['the old argument for',['the original argument for','the traditional case for'],2],['the new argument is that',['the newer argument is that','now the argument is that'],2],
    ['second-order effect',['less obvious effect','downstream effect'],3],['nobody warned me about',['i did not expect','that caught me by surprise'],1],["open question i don't have a good answer to",["one question i still can't answer",'an unresolved question for me'],3],
    ['curious whether anyone has found',["i'd be interested to know whether anyone has found",'i wonder whether anyone has found'],3],['the pattern i keep seeing',['a pattern i keep noticing','i keep seeing the same pattern'],3],['the pattern i keep noticing',['a pattern i keep seeing','i keep noticing the same pattern'],3],
    ["what's helped me",['what works for me',"i've found it helps to"],3],['the other underrated one',['another underappreciated one','another thing people underestimate'],3],["i'm convinced",['i suspect','i strongly suspect'],2],
    ['on a schedule',['on command','at a set time'],2],['the whole thing',['what matters','the important part'],1],['in the room',['there'],1],['logging the hours',['putting in the time','showing up consistently'],2],
    ['regression safety',['protection against regressions'],3],['the interface through which',['the interface that lets','the channel through which'],2],['spot check',['sample-check','check a sample'],2],
    ['logistics friction',['logistical hassle','logistics problems'],3],['running on',['functioning on','operating on'],2],['arrival day',['the day you arrive'],3],['sightseeing day',['day for sightseeing'],3],['written-down plan',['written plan'],3],
    ['mid-trip',['in the middle of the trip'],2],['light day',['easy day','low-key day'],2],['friction point',['recurring hassle','sticking point'],2],
    ['it is possible that',['perhaps','possibly'],1],['there is a chance that',['possibly','perhaps'],1],['the key point is',['the main point is'],2],['one of the key',['one of the main'],2],
    ['do not',['don\'t'],2],['does not',['doesn\'t'],2],['did not',['didn\'t'],2],['is not',['isn\'t'],2],['are not',['aren\'t'],2],['was not',['wasn\'t'],2],['were not',['weren\'t'],2],
    ['cannot',['can\'t'],2],['could not',['couldn\'t'],2],['would not',['wouldn\'t'],2],['should not',['shouldn\'t'],2],['will not',['won\'t'],2],['have not',['haven\'t'],2],['has not',['hasn\'t'],2],['had not',['hadn\'t'],2],
    ['it is',['it\'s'],1],['that is',['that\'s'],1],['there is',['there\'s'],1],['they are',['they\'re'],1],['we are',['we\'re'],1],['you are',['you\'re'],1]
  ];
